language: node_js

node_js:
  - '13.6.0'
  
cache: yarn

install:
  - yarn install

script: npm install codecov -g && yarn test

deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

after_success:
  - codecov